src/Entity/Manuscript.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\ManuscriptRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;



#[ORM\Entity(repositoryClass: ManuscriptRepository::class)]
#[Vich\Uploadable] 
class Manuscript
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $title;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $description;

    #[ORM\Column(type: 'boolean')]
    private $explicitContent = false;

    #[ORM\Column(type: 'string', length: 255)]
    private $readership;


    // User est propriétaire de la relation
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'manuscript')]
    private $users;

    // Question est propriétaire de la relation
    #[ORM\ManyToMany(targetEntity: Question::class, mappedBy: 'manuscripts')]
    private $questions;

    #[ORM\OneToMany(mappedBy: 'manuscriptId', targetEntity: Chapter::class)]
    private $chapters;

    //Manuscript est propriétaire de la relation
    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'manuscripts' )]
    private $author_id;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $imageName;

    /**
    * NOTE: This is not a mapped field of entity metadata, just a simple property.
    */
    #[Vich\UploadableField(mapping: 'manuscripts', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'datetime_immutable')]
    private $updatedAt;

    // Manuscript est propriétaire de la relation
    #[ORM\ManyToMany(targetEntity: Genre::class, inversedBy: 'manuscripts')]
    private $genres;

    //Reporting est propriétaire de la relation
    #[ORM\OneToMany(mappedBy: 'manuscript', targetEntity: Reporting::class)]
    private $reportings;

    #[ORM\Column(type: 'string', length: 255)]
    private $author;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->genres = new ArrayCollection();
        $this->questions = new ArrayCollection();
        $this->chapters = new ArrayCollection();
        $this->reportings = new ArrayCollection();
    }

     /**
    * @return string|null
    */
    public function __toString()
    {
        
        return $this->title;
        return $this->genres;

    }


    public function getId(): ?int
    {
        return $this->id;
    }


    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addManuscript($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeManuscript($this);
        }

        return $this;
    }

    // /**
    //  * @return Collection|Genre[]
    //  */
    // public function getGenres(): Collection
    // {
    //     return $this->genres;
    // }

    // public function addGenre(Genre $genre): self
    // {
    //     if (!$this->genres->contains($genre)) {
    //         $this->genres[] = $genre;
    //         $genre->addManuscript($this);
    //     }

    //     return $this;
    // }

    // public function removeGenre(Genre $genre): self
    // {
    //     if ($this->genres->removeElement($genre)) {
    //         $genre->removeManuscript($this);
    //     }

    //     return $this;
    // }

    /**
     * @return Collection|Question[]
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
            $question->addManuscript($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->removeElement($question)) {
            $question->removeManuscript($this);
        }

        return $this;
    }

    public function getAuthorId(): ?User
    {
        return $this->author_id;
    }

    public function setAuthorId(?User $author_id): self
    {
        $this->author_id = $author_id;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @return Collection|Chapter[]
     */
    public function getChapters(): Collection
    {
        return $this->chapters;
    }

    public function addChapter(Chapter $chapter): self
    {
        if (!$this->chapters->contains($chapter)) {
            $this->chapters[] = $chapter;
            $chapter->setManuscriptId($this);
        }

        return $this;
    }

    public function removeChapter(Chapter $chapter): self
    {
        if ($this->chapters->removeElement($chapter)) {
            // set the owning side to null (unless already changed)
            if ($chapter->getManuscriptId() === $this) {
                $chapter->setManuscriptId(null);
            }
        }

        return $this;
    }

    public function getExplicitContent(): ?bool
    {
        return $this->explicitContent;
    }

    public function setExplicitContent(bool $explicitContent): self
    {
        $this->explicitContent = $explicitContent;

        return $this;
    }

    public function getReadership(): ?string
    {
        return $this->readership;
    }

    public function setReadership(string $readership): self
    {
        $this->readership = $readership;

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }

    /**
     * @return Collection|Reporting[]
     */
    public function getReportings(): Collection
    {
        return $this->reportings;
    }

    public function addReporting(Reporting $reporting): self
    {
        if (!$this->reportings->contains($reporting)) {
            $this->reportings[] = $reporting;
            $reporting->setManuscript($this);
        }

        return $this;
    }

    public function removeReporting(Reporting $reporting): self
    {
        if ($this->reportings->removeElement($reporting)) {
            // set the owning side to null (unless already changed)
            if ($reporting->getManuscript() === $this) {
                $reporting->setManuscript(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }


}

src/Controller/AdminReportingController.php
<?php

namespace App\Controller;

use App\Data\SearchData;
use App\Form\SearchType;
use App\Entity\Reporting;
use App\Form\ReportingType;
use App\Repository\ChapterRepository;
use App\Repository\ReportingRepository;
use App\Repository\ManuscriptRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/admin/reporting')]
class AdminReportingController extends AbstractController
{
    #[Route('/', name: 'admin_reporting_index', methods: ['GET', 'POST'])]
    public function index(ReportingRepository $reportingRepository, Request $request): Response 
    {
        $data = new SearchData();
        $form = $this->createForm(SearchType::class, $data);
        $form->handleRequest($request);
        

        $reportings = $reportingRepository->findSearch($data);
        
        
        
        return $this->render('admin_reporting/index.html.twig', [
            'reportings' => $reportings,
            'form' => $form->createView(),
        
        ]);
    }

    #[Route('/new/manuscript/{manuscriptId}/chapter/{chapterId}', name: 'admin_reporting_new', methods: ['GET', 'POST'])]
    public function new(int $manuscriptId, int $chapterId, Request $request, EntityManagerInterface $entityManager, ManuscriptRepository $manuscriptRepository, ChapterRepository $chapterRepository): Response
    {
        // Au moment de la création du reporting liaison avec le manuscript et le chapter.
        $reporting = new Reporting();
        $form = $this->createForm(ReportingType::class, $reporting);
        $form->handleRequest($request);

        $manuscript = $manuscriptRepository->findOneBy(['id' => $manuscriptId]);
        $author = $manuscript->getAuthorId();
        $chapter = $chapterRepository->findOneBy(['id' => $chapterId]);
        $reporting->setManuscript($manuscript);
        $reporting->setChapter($chapter);
        $reporting->setUser($author);


        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reporting);
            $entityManager->flush();

            $this->addFlash('success', 'Votre signalement a bien été pris en compte.');

            // return $this->redirectToRoute('admin_reporting_index', [], Response::HTTP_SEE_OTHER);
            return $this->redirectToRoute('manuscript_chapter', [
                    'manuscriptId' =>  $manuscriptId,
                    'chapterId' => $chapterId,
            ], Response::HTTP_SEE_OTHER);

        }

        return $this->renderForm('admin_reporting/new.html.twig', [
            'reporting' => $reporting,
            'form' => $form,
            'manuscriptId' => $manuscriptId,
            'chapterId' => $chapterId,
        ]);
    }

    #[Route('/{id}/manuscript/{manuscriptId}/chapter/{chapterId}', name: 'admin_reporting_show', methods: ['GET'])]
    public function show(Reporting $reporting, int $manuscriptId, int $chapterId, ManuscriptRepository $manuscriptRepository, ChapterRepository $chapterRepository): Response
    {
        $manuscript = $manuscriptRepository->findOneBy(['id' => $manuscriptId]);
        $chapter = $chapterRepository->findOneBy(['id' => $chapterId]);

        return $this->render('admin_reporting/show.html.twig', [
            'reporting' => $reporting,
            'manuscriptId' => $manuscriptId,
            'chapterId' => $chapterId,
        ]);
    }

    #[Route('/{id}/edit/manuscript/{manuscriptId}/chapter/{chapterId}', name: 'admin_reporting_edit', methods: ['GET', 'POST'])]
    public function edit(int $manuscriptId, int $chapterId, Request $request, Reporting $reporting, EntityManagerInterface $entityManager, ManuscriptRepository $manuscriptRepository, ChapterRepository $chapterRepository): Response
    {
        $form = $this->createForm(ReportingType::class, $reporting);
        $form->handleRequest($request);

        $manuscript = $manuscriptRepository->findOneBy(['id' => $manuscriptId]);
        $chapter = $chapterRepository->findOneBy(['id' => $chapterId]);

        // $manuscriptId = $reporting->getManuscript();
        // $chapterId = $reporting->getChapter();

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('admin_reporting_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_reporting/edit.html.twig', [
            'reporting' => $reporting,
            'form' => $form,
            'manuscriptId' => $manuscriptId,
            'chapterId' => $chapterId
        ]);
    }

    #[Route('/{id}', name: 'admin_reporting_delete', methods: ['POST'])]
    public function delete(Request $request, Reporting $reporting, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reporting->getId(), $request->request->get('_token'))) {
            $entityManager->remove($reporting);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_reporting_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_reporting/_delete_form.html.twig
<form method="post" action="{{ path('admin_reporting_delete', {'id': reporting.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reporting.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/admin_reporting/_filter.html.twig
{{ form_start(form) }}


<div class='row'>
        <div class='col-md-6'>
            {{ form_row(form.authors) }}
            <button type='submit' class='btn btn-primary w-100'>Filtrer</button>
        </div>    

</div>

    
{{ form_end(form) }}

templates/admin_reporting/_form.html.twig
{{ form_start(form, {'action' : path('admin_reporting_new', {'chapterId': chapterId, 'manuscriptId': manuscriptId} )}) }}
    {{ form_widget(form) }}
    <button class="btn btn-success" id="formButton">{{ button_label|default('Envoyer') }}</button>
{{ form_end(form) }}

{# {'action' : path('admin_reporting_new', {'chapterId': chapterId, 'manuscriptId': manuscriptId} )} #}

templates/admin_reporting/edit.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %}Edit Reporting{% endblock %}

{% block body %}
    

    <div class="d-flex flex-row justify-content-between">
        <h1> Modifier un signalement </h1>
        <a href="{{ path('admin_reporting_index') }}" class="btn btn-dark mb-3" ><strong> Retourner à la liste </strong></a>
    </div>


    {{ include('admin_reporting/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
    {{ include('admin_reporting/_delete_form.html.twig') }}


{% endblock %}

templates/admin_reporting/index.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %}Reporting index{% endblock %}

{% block body %}
    <h1>Signalements</h1>


    <div class="col-md-3">
            {% include 'admin_reporting/_filter.html.twig'%}
    </div>
    

    <table class="table">
        <thead>
            <tr>
                
                <th>Contenu</th>
                <th>Chapitre</th>
                <th>Auteur</th>
                
            </tr>
        </thead>
        <tbody>
        {% for reporting in reportings %}
            <tr>
                <td>{{ reporting.content }}</td>
                <td>{{ reporting.chapter.title }}</td>
                <td>{{ reporting.manuscript.authorId.email }}</td>
                <td class="text-end">
                    <a href="{{ path('admin_reporting_show', {'chapterId': reporting.chapter.id, 'manuscriptId': reporting.manuscript.id, 'id': reporting.id}) }}" class="btn btn-primary"><i class="align-middle" data-feather="eye"></i></a></a>
                    <a href="{{ path('admin_reporting_edit', {'chapterId': reporting.chapter.id, 'manuscriptId': reporting.manuscript.id, 'id': reporting.id}) }}" class="btn btn-success"><i class="align-middle" data-feather="edit-2"></i></a>
                </td>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('admin_reporting_new') }}">Create new</a> #}
{% endblock %}

templates/admin_reporting/new.html.twig
{% block title %}{% endblock %}

{% block body %}

    {{ include('admin_reporting/_form.html.twig') }}

    
{% endblock %}


{# {% block javascripts %}
	 <script>
	 $(document).ready(function(){	
	    $("#formButton").submit(function(event){
		submitForm();
		return false;
	});
});

function submitForm(){
	$.ajax({
		type: "POST",
		url: path('App\\Controller\\AdminReportingController::new'),
		cache:false,
		data: $('form#formModal).serialize(),
		/*success: function(response){
			$("#contact").html(response)
			$("#contact-modal").modal('hide');
		},*/ 
		error: function(){
			alert("Error");
		});
	});
}
</script>  #}
	
   
	
{# A qui je dois envoyer la requête (paramètre: url) ? #}
    {# // Url : définis le script ou la ressource à appeler.
    $(document).ready(function() {
        $("#formButton").submit("click",function(e) {
           $.ajax({
        url : path('App\\Controller\\AdminReportingController::new'),
        data: {"donnees":[]},//tes données à envoyer
        type : POST,
        //success : function(data) {
        //    $('.modal-body').html(data); // Utiliser un id serait plus précis        
		//}
        });
        return false;
       }); 
	});#}










	{# {% endblock %} #}

templates/admin_reporting/show.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %}Reporting{% endblock %}

{% block body %}
    <h1>Reporting</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reporting.id }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ reporting.content }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('admin_reporting_index') }}">back to list</a>

    <a href="{{ path('admin_reporting_edit', {'chapterId': reporting.chapter.id, 'manuscriptId': reporting.manuscript.id, 'id': reporting.id}) }}">edit</a>

    {{ include('admin_reporting/_delete_form.html.twig') }}
{% endblock %}